framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'dentaltea@autismocordoba.org'
        headers:
            From: 'DentalTEA <dentaltea@autismocordoba.org>'
